# Generated by Django 4.2.10 on 2024-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="id",
        ),
        migrations.AddField(
            model_name="note",
            name="note_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
